### ISSUE TITLE
noCoverage option check incorrect?

### ISSUE THREAD

**Issue by jacksleight** [mikeerickson/gulp-phpunit#104]
There's an option called `opt.noCoverage`, which is set to false by default, and I would _assume_ should add the `--no-coverage` phpunit argument if set to true? (It's not documented in the README.)

However, the code does the opposite:

```js
if ((! skip) && (! opt.noCoverage)) {
	cmd += ' --no-coverage ';
}
```

So doing:

```js
.pipe(phpunit('...', {noCoverage: true}));
```

Results in coverage reports being generated (if configured), and:

```js
.pipe(phpunit('...', {noCoverage: false}));
```

Results in no coverage reports being generated.

Not sure if this is a bug or intended behaviour, but if it's intended it seems pretty unintuitive. As the default is false it also means that `--no-coverage` is always set by default with a blank config.

**Comment by mikeerickson** [comment]
@jacksleight good catch, I have adjusted code accordingly :-)
