### ISSUE TITLE
noCoverage option not used if using a configuration file

### ISSUE THREAD

**Issue by boba** [mikeerickson/gulp-phpunit#116]
Adding { noCoverage: true } to the options does not add the "--no-coverge" argument to phpunit if you have also specified a configuration file via either gulp-src('phpunit.xml') or with { configurationFile: 'phpunit.xml' }.  This option should be allowed even if code coverage is defined in the configuration file.

The code below shows that 'skip' is set to true if an .xml configuration file is specified. 'skip' is then later checked to allow the no-coverage option. 

```javascript
    if ((file.path) && (! skip) && (!opt.noConfiguration)){
      var ext = file.path.substr(file.path.lastIndexOf('.') + 1);
      if ( ext === 'xml') {
        cmd += ' -c "' + file.path + '"'; skip = true;
      }
    }
    // ...
    if ((! skip) && (opt.noCoverage)) {
      cmd += ' --no-coverage ';
    }
```

Better would be to do something like this:

```javascript
  /* code coverage */
    if(opt.coverageClover)      { cmd += ' --coverage-clover=' + opt.coverageClover; }
    // ...
    if(opt.noCoverage)          { cmd += ' --no-coverage'; }
```

**Comment by mikeerickson** [comment]
Thanks for the report, I will get it updated in the next few days (likely weekend work)

**Comment by boba** [comment]
You rock. Thanks!
