### ISSUE TITLE
Error: stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by ejunker** [mikeerickson/gulp-phpunit#19]
I'm using some dataProviders with many test cases. I am running my tests with the debug flag like this

`phpunit --group=search --colors --debug`

The combination of using data providers and the debug flag result in a lot of test output which I believe is what causes maxBuffer to be exceeded.

It looks like the fix may be to use child_process.spawn instead of child_process.exec https://github.com/notatestuser/gift/issues/23

**Comment by mikeerickson** [comment]
@ejunker I will take a look and see if your suggestion indeed fixes your problem.   If you want to get adventerous, make the change in the index.js file (at the top) and give it a whirl (that is what i would to test it).
