### ISSUE TITLE
Phpunit on windows

### ISSUE THREAD

**Issue by mnshankar** [mikeerickson/gulp-phpunit#21]
Hi,
As of now, gulp-Phpunit does not work on windows.

I would like to recommend a minor fix to file
index.js around line 85.

(this presumes the user has installed git tools and added the location to the included unix tools in their path variable)
```
if (os.platform() === 'win32') {
    command = 'bash vendor/bin/phpunit';
}
```

**Comment by mikeerickson** [comment]
But it does work on windows, I use it all the time.   As stated in docs, the first parameter is the path to wherever you have phpunit installed.  

And it does not require git to be installed to use it either.

**Comment by mnshankar** [comment]
Thanks for your prompt response. 
Let me back up a little and explain the context of my ticket. 

I recently started using Laravel/Elixir to automate my testing process. As you will note here: https://github.com/laravel/elixir/blob/master/ingredients/commands/RunTests.js, Elixir uses gulp-phpunit as described in #3 of your docs (supply callback to integrate something like notification (using gulp-notify)) - this defaults phpunitpath  to ./vendor/bin/phpunit.

Now, on my PC, the error I get on running this is 
```
'.\vendor\bin\phpunit' is not recognized as an internal or external command,
operable program or batch file.
```
1. This error goes away on changing the default command as described in my initial request
2. How do I pass a phpunitpath in this case

**Comment by mikeerickson** [comment]
@mnshankar I am not using it with Laravel Elixir, so I cant comment on that configuration.  I am using it on windows strait out of the box, but that it works as my path to phpunit binary matches the default location configured in gulp-phpunit.

As you described in item 2 above, the path will need to be overriden if it is not in the default location (which is the reason property is supplied.

````
var phpunit = require('gulp-phpunit);

gulp.task('phpunit', function() {
  return gulp.src('./phpunit.xml')
    .pipe(phpunit('path/to/bin/here';options);
});

````

As I recall, using with Elixir, it should expose all the same properties, etc. as supplied using gulp-phpunit plugin (the parameters you supply should match signature outlined above)

**Comment by mikeerickson** [comment]
@mnshankar please refer to this section of documentation as it contains a working example of how to use on windows as well


````

// Note: Windows OS may require double backslashes if using other than default location (option 1)
gulp.task('phpunit', function() {
  gulp.src('phpunit.xml').pipe(phpunit('.\\path\\to\\phpunit'));
});

````
