### ISSUE TITLE
ParsePI: PI php never end ...

### ISSUE THREAD

**Issue by micc83** [mikeerickson/gulp-phpunit#23]
Hi,

After updating to 0.8.1 I get the error:

```sh
 *** Debug Cmd: ./vendor/bin/phpunit --colors --debug --c /myPath/tests/RoleRepoTest.php ***

Could not load "/myPath/tests/RoleRepoTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found
```

In order to fix it, accordingly to this [stackoverflow question](http://stackoverflow.com/questions/16860104/setting-phpunit-command-from-the-console-symfony), I have updated [index.js#L173](https://github.com/mikeerickson/gulp-phpunit/blob/master/index.js#L173) replacing the `-c` attribute with `--bootstrap`.

**Comment by mikeerickson** [comment]
Updated in gulp-phpunit 0.8.3

**Comment by mikeerickson** [comment]
@micc83 Can you please test against the 0.8.3 version just updated.

**Comment by jadjoubran** [comment]
The bug is still occurring
Source: https://github.com/mikeerickson/gulp-phpunit/blob/master/index.js#L176

Reference: https://laracasts.com/discuss/channels/testing/gulp-tdd-not-working-properly
