### ISSUE TITLE
Latest update breaks with 'Could not read "-bootstrap".'

### ISSUE THREAD

**Issue by burriko** [mikeerickson/gulp-phpunit#24]
I've just updated to 0.8.3 and now the arguments ' -c -bootstrap' are being added to PHPUnit, which seems to be incorrect. PHPUnit ends up trying to load a config file named '-bootstrap'.

**Comment by VoodooPrawn** [comment]
+1, I just changed index.js:176 to: cmd += ' -c "' + file.path + '"';

Seems to be working now.

**Comment by mikeerickson** [comment]
Thx for info, I will get this updated in release version this evening.

**Comment by slayerfat** [comment]
can confirm @VoodooPrawn solution does work

**Comment by mikeerickson** [comment]
@slayerfat @VoodooPrawn 

Hey guys, I have updated the plugin and submitted to npm.   Please let me know if you have any further issues.

**Comment by mikeerickson** [comment]
This has been fixed in 0.9.0, please update :-)    

I didnt use your PR, but I do appreacite it as it helped track down the _real_ issue
