### ISSUE TITLE
Using Laravel Elixir 3.0 with gulp-phpunit version 0.9.0: ParsePI: PI php never end

### ISSUE THREAD

**Issue by Arceopteryx** [mikeerickson/gulp-phpunit#29]
Hello

I've seen that you have fixed this issue once before. I am following a book in order to learn Laravel. When using the gulp command it gives me this error:

```
[20:53:45] Using gulpfile ~/Code/l5beauty/gulpfile.js
[20:53:45] Starting 'default'...
[20:53:45] Starting 'phpUnit'...

Fetching PhpUnit Source Files...
   - tests/**/*Test.php

[20:53:45] Finished 'default' after 13 ms
[20:53:45] 

       *** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c "/Users/arc/Code/l5beauty/tests/ExampleTest.php" ***

Could not load "/Users/arc/Code/l5beauty/tests/ExampleTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found

[20:53:45] Could not load "/Users/arc/Code/l5beauty/tests/ExampleTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found
[20:53:45] { [Error: Command failed: /bin/sh -c ./vendor/bin/phpunit --colors --debug -c "/Users/arc/Code/l5beauty/tests/ExampleTest.php"
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c ./vendor/bin/phpunit --colors --debug -c "/Users/arc/Code/l5beauty/tests/ExampleTest.php"' }
```

Tried replacing the -c flag in index.js with --bootstrap according to the previous issue listing, but with no cigar.

EDIT: There is a user at the laracasts forum that claims that it is an issue with Elixir 3.0 https://laracasts.com/discuss/channels/elixir/elixir-no-longer-running-phpunit

EDIT 2: JeffreyWay has responded with a fix. Do the following in the gulpfile.js

```
mix.phpUnit('phpunit.xml');
```

This solves my issue. Am I using the wrong version of gulp-phpunit?

**Comment by mikeerickson** [comment]
@Arceopteryx Yes, using the above Elixir command will indeed cure your issue.  However, this has also been resolved in gulp-phpunit 

$ npm install -S gulp-phpunit@0.9.0 <-- we also have 0.9.1

Due to the way Jeffrey has configured his package.json, it will only pull in versions < 0.9.0 (ie 0.8.x)
