### ISSUE TITLE
gulp-phplint?

### ISSUE THREAD

**Issue by henrywright** [mikeerickson/gulp-phpunit#33]
Why does the README.md speak of `gulp-phplint`? I thought the plugin was `gulp-phpunit`.

Ref: https://github.com/mikeerickson/gulp-phpunit

**Comment by mikeerickson** [comment]
it is indeed gulp-phpunit.  My bad (I was working on both plugins the same day and made a mistake

**Comment by mikeerickson** [comment]
@henrywright Thank you for bringing this to my attention.  The issue is much deeper than just the readme.  The whole project is messed up.   I will get this cured over the weekend.

THANK YOU!

**Comment by mikeerickson** [comment]
@henrywright The plugin repository on npm is still available... 

$ npm install -D gulp-phpunit

**Comment by henrywright** [comment]
No problem @mikeerickson, the node package does indeed work great on my local machine. hope you're able to fix the Git repo

**Comment by mikeerickson** [comment]
@henrywright All fixed :-)  Thanks again
