### ISSUE TITLE
option --colors doesn't allow an argument

### ISSUE THREAD

**Issue by henrywright** [mikeerickson/gulp-phpunit#34]
I'm getting this message when I run my gulp task:

> option --colors doesn't allow an argument

Thing is, I'm not providing a `--colors` option in my task or in my `phpunit.xml`. My task:
```
gulp.task('phpunit', function() {
	return gulp.src('phpunit.xml')
		.pipe(phpunit('phpunit'));
});
```

Here's my build log: https://travis-ci.org/henrywright/buddypress-identicons/jobs/104960524

**Comment by mikeerickson** [comment]
Two questions

1) what version of gulp-phpunit are you using 
2) can you please the gulp task which uses plugin

**Comment by henrywright** [comment]
1) 0.11.3

2) I did paste my task above, but here it is again
```
gulp.task('phpunit', function() {
    return gulp.src('phpunit.xml')
        .pipe(phpunit('phpunit'));
});
```

**Comment by mikeerickson** [comment]
@henrywright My apologies requesting the task, I was responding on phone and didn't see that part.

This appears to be an issue with the version of PHPUnit you are using.   What version of PHPUnit are you using?  I will have a look using the same version you are using locally and see what is happening.

**Comment by henrywright** [comment]
4.5.0 is the version I'm seeing the problem. I'm running 4.8.21 locally which is working fine.

**Comment by mikeerickson** [comment]
This extended --colors=always was added in 4.8.x series. In 4.5, the --colors was all it had.

**Comment by henrywright** [comment]
I'm not specifying `--colors=always` or `--colors`. Is that something gulp-phpunit does?

**Comment by mikeerickson** [comment]
@henrywright I have fixed this issue, just need to upgrade to gulp-phpunit v0.12.1 or greater

$ npm i -D gulp-phpunit@latest

**Comment by henrywright** [comment]
Thanks Mike!
