### ISSUE TITLE
Task is reporting as finished before actually finishing

### ISSUE THREAD

**Issue by alexpica** [mikeerickson/gulp-phpunit#41]
Hey

I declared a task running phpunit like this: 

```
gulp.task('test-php', ['get-phpunit'], function(done){
     gulp.src('./phpunit.xml')
        .pipe(phpunit('php phpunit.phar'))
        .on('end', done);
});
```

But when i run it, it doesn't wait until the actual end of the command.

> [14:56:04] Starting 'test-php'...
> PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
> [14:56:04] Finished 'test-php' after 353 ms
> 
> ............F
> 
> Time: 600 ms, Memory: 11.75Mb
> 
> There was 1 failure: ....

So if i try to put it in a sequential task list, it runs it in parallel with the next item (in fact the phpunit task returns immediately, while the actual phpunit command still runs + it runs the next item in the list).

Maybe it's something i'm doing wrong?

Thanks,
Alex

**Comment by KOGI** [comment]
Running into the same thing here. I've spent a few hours digging and it *seems* like it's related to the way this lib is using map-stream, but I'm really not sure.

**Comment by mikeerickson** [comment]
@alexpica @KOGI 

Can you please run with debug enabled and send me a screen of output

```
.pipe(phpunit('php phpunit.phar', {debug: true}))
```

**Comment by KOGI** [comment]
##### note: this is using gulp-phpunit v0.11.3 because I couldn't get the upgrade to v0.14.0 working at all (missing dependencies)

## gulpfile.js

```
var gulp    = require( 'gulp' );
var phpunit = require( 'gulp-phpunit' );
var exec    = require( 'child_process' ).exec;

gulp.task( 'test', ['_notify-start'], function() {
	var options = {
		configurationFile : 'tests/unit/config.xml',
		testSuite         : 'unit.api',
		statusLine        : false,
		clear             : false,
		debug             : true,
	};

	console.log( "\n" + '-------- start' );
	return gulp.src('')
		.pipe( phpunit( './vendor/bin/phpunit', options ))
		.on( 'end', function() {
			console.log( '-------- finish' + "\n" );
		});
});
```

## Output

```
user@host:prompt$ gulp test
[22:43:22] Using gulpfile ~/path/to/gulpfile.js
[22:43:22] Starting 'test'...

-------- start

       *** [Version] 0.11.3 Debug Cmd: ./vendor/bin/phpunit --colors=always --debug -c tests/unit/config.xml --testsuite unit.event ***

-------- finish
[22:43:23] Finished 'test' after 441 ms

PHPUnit 5.2.3 by Sebastian Bergmann and contributors.

...............................................................  63 / 102 ( 61%)
.......................................                         102 / 102 (100%)

Time: 8.22 seconds, Memory: 15.50Mb



OK (102 tests, 165 assertions)

Generating code coverage report in HTML format ... done
```

Notice gulp output of `Finished 'test' after 441 ms` and phpUnit output of `Time: 8.22 seconds`

**Comment by mikeerickson** [comment]
@KOGI Actually, this is nothing I have control over, it is the way gulp works.   These start and finish items are created by gulp internally.  Since gulp-phpunit starts a new process (async) to execute PHPUnit, it is spawned and left to complete on its own.

Having said that, I am going do some research to see if I can control the actual finish of the gulp task.

**Comment by KOGI** [comment]
That would be awesome
