### ISSUE TITLE
Unhandled error on failure of phpunit 

### ISSUE THREAD

**Issue by Starli0n** [mikeerickson/gulp-phpunit#46]
Hi,

It seems that I do not manage to handle the error from phpunit but I do not know why...

Here is my script:

````
var phpunit = require('gulp-phpunit');
var notify  = require('gulp-notify');

gulp.task('server:test', function () {
    //phpunit --coverage-html=./report --bootstrap=./test/bootstrap.php --configuration=./test/phpunit.xml
    var options = {
        notify: true,
        coverageHtml: paths.report,
        bootstrap: files.bootstrap
    };
    return gulp.src(files.phpunit)
        .pipe(phpunit('', options))
        // #1
        //.on('error', process.exit.bind(process, 1));
        // #2
        /*.on('error', function() {
            console.error('PHPUnit failed!!!!!!!!!!!!');
        });*/
        // #3
        .on('error', notify.onError({
            title: "Failed Tests!",
            message: "Error(s) occurred during testing..."
        }));
});
````

When I run the gulp task, I can see the `phpunit` output with a failure as expected in the console but it seems that the plugin always return 0. As a consequence, I could not reach `on('error', ...)`. I tried with the 3 methods, in vain...

Could you please help me on this ?

Thanks

**Comment by mikeerickson** [comment]
@Starli0n I will have a look at this ASAP   I have a solution in mind, but need to code / test it for sure.

**Comment by mikeerickson** [comment]
@Starli0n Version 0.17.0 https://www.npmjs.com/package/gulp-phpunit has a new callback you can execute when each test case is run

      ```
      gulp.task('phpunit', function() {
        gulp.src('')
          .pipe(phpunit('phpunit.xml', opts, function(err, success){
            if(err) { throw err }
            console.log(success)
          });
      });
      ```

**Comment by Starli0n** [comment]
Thanks, it works! (I prefer using `process.exit(1);` instead of `throw err`)

**Comment by mikeerickson** [comment]
@Starli0n Whatever you prefer, that is up to you :-) 

By supplying a callback, it gives YOU the tools you need to do it however you wish.
